BEGIN;

CREATE TABLE patients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ho_va_ten VARCHAR(200) NOT NULL,
    gioi_tinh VARCHAR(20) NOT NULL,
    ngay_sinh DATE NOT NULL,
    giay_to_tuy_than VARCHAR(100),
    so_the_bhyt VARCHAR(100),
    dia_chi TEXT,
    nghe_nghiep VARCHAR(200),
    dan_toc VARCHAR(100),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE visits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL,
    tt INTEGER NOT NULL,
    ngay_kham DATE NOT NULL,
    trieu_chung TEXT NOT NULL,
    chan_doan TEXT NOT NULL,
    phuong_phap_dieu_tri TEXT NOT NULL,
    bac_si_kham VARCHAR(200) NOT NULL,
    ghi_chu TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_visits_patient
        FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE CASCADE
);

CREATE TABLE doanh_thu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visit_id BIGINT NOT NULL,
    so_hieu VARCHAR(100),
    ngay_thang DATE NOT NULL,
    dien_giai TEXT NOT NULL,
    so_tien NUMERIC(15, 2) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_doanh_thu_visit
        FOREIGN KEY (visit_id) REFERENCES visits (id) ON DELETE CASCADE,
    CONSTRAINT chk_doanh_thu_so_tien_nonnegative CHECK (so_tien >= 0)
);

CREATE INDEX idx_patients_ho_va_ten ON patients (ho_va_ten);
CREATE INDEX idx_visits_patient_id ON visits (patient_id);
CREATE INDEX idx_visits_created_at ON visits (created_at);
CREATE INDEX idx_visits_ngay_kham ON visits (ngay_kham);
CREATE INDEX idx_doanh_thu_visit_id ON doanh_thu (visit_id);
CREATE INDEX idx_doanh_thu_ngay_thang ON doanh_thu (ngay_thang);

COMMIT;
